### ISSUE TITLE
Invalid GUILayout on Unity 2023.3

### ISSUE THREAD

**Issue by Pholith** [NibbleByte/UnityAssetManagementTools#2]
Hello,
I'm getting the error `GUI Error: Invalid GUILayout state in SearchDuplicateAssets view. Verify that all layout Begin/End calls match
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`
when trying to delete a duplicate asset.
I use unity 2023.3.0b5

**Comment by Pholith** [comment]
To fix it:
Add `GUILayout.EndHorizontal();` before the `continue` of SearchDuplicateAssets line 145

**Comment by NibbleByte** [comment]
Good catch. I've solved it by calling `GUIUtility.ExitGUI();` instead.
I've also did some facelift of how the results are displayed.
Result entries are now foldable + added Collapse/Expand all buttons.
Added Delete asset button.
![image](https://github.com/NibbleByte/UnityAssetManagementTools/assets/2332996/681650e0-e626-4794-bb9c-2ec69b5258cf)

**Comment by Pholith** [comment]
Oh that's really nice, thanks
Do the delete button also change the reference in prefabs/scene objects? For example if I have 2 differents prefabs with the same texture, if I delete one, will it target the other texture ?
If not I plan to work on that, I didn't find any  repository thid complete on assets and duplicate management.

**Comment by NibbleByte** [comment]
No, that would require a lot more work, like searching through the whole project and saving assets (prefabs, scenes, prefab overrides, materials). I wouldn't trust me to do it properly 😄 

You can check out the Unity experimental [Dependency Viewer](https://forum.unity.com/threads/experimental-dependency-viewer.1158899/). It scans all the references in your project and builds a look up cache. Once built, you can quickly check which assets are used by who. Drawback is - if you change your assets, you need to update the cache, which takes about a minute for a 90 GB project. Also it's a bit buggy as it is experimental (logs error sometimes), but nothing game-breaking. It will help you hunt down the duplicate references usage.
If you want something more stable, I know there are similar plugins on the asset store, but haven't used them.

**Comment by Pholith** [comment]
Thanks I didn't know Dependency Viewer, but it's still really buggy in new unity versions and doesn't fit my need.
I took a look at FindReference2 and AssetHunter pro, but sadly the first was perfect but is not maintened anymore and doesn't work now, and the second doesn't do it automaticly, it just list it like this tool https://github.com/Tymski/UnityDuplicateAssetDetector. And other tools doesn't do that.
Finally I'm not sure to work on it yet, it looks like a quite difficult work, maybe should I make an issue to note it for someone else in need? I think it could help enhance this open source project and that can be nice.

**Comment by NibbleByte** [comment]
If you want to redirect your references, you can find-replace as text the guids in all assets where they are met with Notepad++ or any other text editing software.
Open any material, prefab or scene with text editor and you'll notice that references are stored like this:
`{fileID: 6986883487782155098, guid: af7e5b759d61c1b4fbf64e33d8f248dc, type: 3}`
(note this can be on 2 lines)

You can easily replace the fileID and guid to what you desire.
Each asset file has guid that is unique in the whole project, while fileIDs refer to objects inside that asset file (for example, child game objects in prefab, animation clips in fbx, etc), i.e. sub assets. Those can be obtained with `AssetDatabase.TryGetGUIDAndLocalFileIdentifier()`.

That is if you're in the mood for some hard-core tooling... 😄
